trust_level:
  type: string
  default: "1"
  description: "Minimum trust level to see the button."
composer_empty_post_button_icon:
  type: string
  default: "far-file"
  description: "Change empty post button icon."
svg_icons: 
  default: "far-file"
  type: "list"
  list_type: "compact"
  description: "List of FontAwesome 5 icons used in this theme component."
put_in_popup_menu:
  type: bool
  default: true
  description: "Add the empty post button to popup options menu. Uncheck this to put it to toolbar section."  
composer_empty_post_button_group:
  default: insertions
  type: enum
  choices:
    - fontStyles
    - extras
  description: "Change empty post button group position."
